version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - ~/.aws:/root/.aws
      - ./client:/root/client
      - ./server:/root/server
    ports:
      - 8460:8460
      - 9229:9229
