version: '3'
services:
  app:
    build:
      context: ../graduate-studies-email-spa
    volumes:
      - ~/.aws:/root/.aws
      - ./client:/root/client
      - ./server:/root/server
    ports:
      - 8460:8460
      - 9229:9229
    environment:
      IN_DEV: 1