version: 1

name: grad-studies-enrollment-spa

pipelines:
  stage:
    phases:
    - type: github
      name: GitHub
      owner: byu-oit
      repo: grad-studies-enrollment-spa
      branch: master
    - type: codebuild
      name: CodeBuild
      build_image: aws/codebuild/docker:18.09.0
    - type: handel
      name: StageDeploy
      environments_to_deploy:
      - stage
  prod:
    phases:
    - type: github
      name: GitHub
      owner: byu-oit
      repo: grad-studies-enrollment-spa
      branch: release
    - type: codebuild
      name: CodeBuild
      build_image: aws/codebuild/docker:18.09.0
    - type: handel
      name: ProdDeploy
      environments_to_deploy:
      - prod
